import React from "react";
import { Link } from "react-router-dom";
import { Container } from "../components/ui/Layout";

const EFFECTIVE_DATE = "2 October 2026";

function Placeholder({ children }) {
  return <span className="op-policy-placeholder">To be confirmed: {children}</span>;
}

function PolicyPage({ eyebrow, title, intro, counterpart, sections }) {
  return (
    <div className="op-policy-page">
      <header className="op-policy-hero">
        <Container>
          <p className="op-sales-label">{eyebrow}</p>
          <h1>{title}</h1>
          <p>{intro}</p>
          <dl className="op-policy-meta">
            <div><dt>Effective</dt><dd>{EFFECTIVE_DATE}</dd></div>
            <div><dt>Status</dt><dd>Requires legal review</dd></div>
          </dl>
        </Container>
      </header>

      <section className="op-policy-document">
        <Container>
          <aside className="op-policy-navigation" aria-label={`${title} sections`}>
            <p>On this page</p>
            <ol>
              {sections.map((section) => <li key={section.id}><a href={`#${section.id}`}>{section.title}</a></li>)}
            </ol>
          </aside>

          <article className="op-policy-content">
            <div className="op-policy-review" role="note">
              <strong>Legal review notice</strong>
              <p>This document reflects the implementation that can be verified in Operion&apos;s current website and application. Marked items must be completed and reviewed by the company&apos;s legal or privacy adviser before the document is relied on as final legal wording.</p>
            </div>
            {sections.map((section, index) => (
              <section id={section.id} key={section.id} aria-labelledby={`${section.id}-heading`}>
                <span className="op-policy-section-number" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span>
                <h2 id={`${section.id}-heading`}>{section.title}</h2>
                {section.content}
              </section>
            ))}
            <nav className="op-policy-related" aria-label="Related legal information">
              <span>Related document</span>
              <Link to={counterpart.to}>{counterpart.label}</Link>
            </nav>
          </article>
        </Container>
      </section>
    </div>
  );
}

const privacySections = [
  {
    id: "controller",
    title: "Data controller and company identity",
    content: <><p>The public website and Operion platform are presented under the Operion name. The legal entity responsible for the website has not been identified in the current public configuration.</p><p><Placeholder>legal entity name, registration details, registered address and controller status.</Placeholder></p></>,
  },
  {
    id: "scope",
    title: "Scope",
    content: <><p>This policy covers information handled through the public Operion website, demonstration requests, user accounts and the authenticated Operion platform. It distinguishes four contexts:</p><ul><li><strong>Website visitor data</strong>, including consent choices and basic technical activity.</li><li><strong>User and account data</strong>, used for authentication and access.</li><li><strong>Customer organisation data</strong>, including organisation membership and role information.</li><li><strong>Uploaded contract and document content</strong>, supplied by authorised customer users for contract intelligence workflows.</li></ul><p>Separate customer agreements may apply to a particular deployment and should define the parties&apos; data-protection roles.</p></>,
  },
  {
    id: "information-collected",
    title: "Information collected",
    content: <p>Operion may receive information that a person submits directly, information created through use of the service, and limited technical information generated by the website or its infrastructure. The categories actually collected depend on whether the person is visiting the public site, requesting a demonstration, or using an authorised customer account.</p>,
  },
  {
    id: "accounts-organisations",
    title: "Account and organisation information",
    content: <p>The platform uses account identifiers such as business email addresses for authentication. It also processes organisation identifiers, active membership, assigned roles and permissions to determine access to protected functions. Authentication is provided through the configured Supabase service.</p>,
  },
  {
    id: "contract-documents",
    title: "Contract and document information",
    content: <><p>Authorised users may upload PDF or DOCX contract documents. Operion processes document text and related structure to produce clauses, obligations, deadlines, risks, evidence, summaries and other contract intelligence. Source documents are stored in a private storage bucket using organisation-scoped paths; protected APIs also apply authentication, membership and permission checks.</p><p>Customers should upload only content they are authorised to provide. Public demonstration forms must not be used to submit confidential contracts or credentials.</p></>,
  },
  {
    id: "technical-usage",
    title: "Technical and usage information",
    content: <><p>The website stores an analytics-consent choice in browser local storage. If analytics is allowed, Google Analytics 4 is loaded and receives page-view and selected interaction events; the current configuration requests IP anonymisation. The public demonstration also uses browser session storage for temporary demonstration preferences and interactions.</p><p>Server infrastructure may necessarily process request information such as an IP address to deliver and protect the service, including rate-limiting demonstration requests. The current codebase does not establish a public server-log retention period.</p></>,
  },
  {
    id: "purposes",
    title: "Purposes of processing",
    content: <p>Information is used to provide and secure account access, enforce organisation boundaries, receive and respond to demonstration enquiries, process customer-authorised documents, produce requested contract intelligence, maintain service operation, and understand public website engagement where analytics consent has been given.</p>,
  },
  {
    id: "legal-bases",
    title: "GDPR legal bases",
    content: <><p>Where the UK GDPR, EU GDPR or similar law applies, processing must have an appropriate legal basis. Depending on the context, that may include steps requested before entering a contract, performance of a customer agreement, legitimate interests in operating and securing the service, compliance with legal obligations, or consent for optional analytics.</p><p><Placeholder>the controller&apos;s final lawful-basis assessment, legitimate-interest assessment and applicable GDPR jurisdiction.</Placeholder></p></>,
  },
  {
    id: "ai-processing",
    title: "AI-assisted processing",
    content: <><p>Some supported analysis actions may use an AI gateway when explicitly configured or requested. Core document ingestion and deterministic contract-intelligence stages do not require an external AI provider. Provider configuration, data use, geographic processing and contractual protections may vary by deployment and must be agreed for the applicable customer environment.</p><p>AI-assisted outputs may be incomplete or inaccurate and are intended for review, not as a substitute for professional judgement.</p></>,
  },
  {
    id: "customer-content",
    title: "Customer content and data-protection roles",
    content: <><p>Customer organisations determine which authorised users upload content and initiate analysis. Operion does not claim ownership of customer contract content through this policy. The allocation of controller, processor or other legal roles must be set out in the applicable customer agreement.</p><p><Placeholder>customer data-processing terms and controller/processor allocation.</Placeholder></p></>,
  },
  {
    id: "providers",
    title: "Service providers and subprocessors",
    content: <><p>The current implementation uses configured services that include Supabase for authentication, database and storage functions; Resend for delivery of public demonstration requests; and Google Analytics 4 only after analytics consent. Hosting, AI and other deployment providers depend on the applicable environment.</p><p><Placeholder>approved subprocessor list, purposes, locations and notification process.</Placeholder></p></>,
  },
  {
    id: "transfers",
    title: "International transfers and data location",
    content: <><p>Operion does not make a fixed data-residency or data-sovereignty claim on this website. Processing location and any international transfer safeguards depend on the selected deployment and providers.</p><p><Placeholder>data locations, transfer mechanisms and supplementary safeguards.</Placeholder></p></>,
  },
  {
    id: "retention",
    title: "Data retention",
    content: <><p>The codebase supports deletion of customer contracts and associated records, but it does not define a complete public retention schedule. Different categories may need different periods based on customer instructions, operational need, legal obligations and dispute requirements.</p><p><Placeholder>retention and deletion periods for enquiries, accounts, customer content, backups, analytics and technical logs.</Placeholder></p></>,
  },
  {
    id: "security",
    title: "Security",
    content: <><p>Current controls include authenticated private application routes, active organisation-membership checks, role-based permissions, organisation-scoped database queries, row-level database policies and private document storage policies. Credentials and provider configuration are intended to remain server-side.</p><p>Operion does not claim ISO 27001 or SOC 2 certification, completed penetration testing, guaranteed uptime, immutable audit logs, fixed data residency or universal AI isolation. Deployment-specific controls should be assessed for each customer environment. See the <Link to="/security">Security page</Link>.</p></>,
  },
  {
    id: "rights",
    title: "Data subject rights",
    content: <><p>Depending on applicable law and Operion&apos;s role, individuals may have rights to access, correct, delete or restrict personal data, object to certain processing, request portability, withdraw consent, or complain to a supervisory authority. Requests may require identity verification and may be subject to legal exceptions.</p><p><Placeholder>responsible privacy contact, applicable supervisory authority and request procedure.</Placeholder></p></>,
  },
  {
    id: "cookies-analytics",
    title: "Cookies, local storage and analytics",
    content: <><p>Google Analytics is not loaded until a visitor selects “Allow analytics.” The choice is saved under <code>operion-analytics-consent</code> in local storage. Visitors can reopen Analytics preferences from the footer and change their selection. Declining analytics does not prevent use of the public website.</p><p>Authentication or infrastructure providers may use storage necessary to provide their configured services. A complete deployed-domain cookie inventory must be verified before final publication.</p></>,
  },
  {
    id: "communications",
    title: "Communications",
    content: <p>A demonstration request collects a name, work email, company, role, company type and optional message. The request is delivered to Operion by the configured transactional email provider so that Operion can respond. The current form does not enrol the requester in a marketing mailing list.</p>,
  },
  {
    id: "changes",
    title: "Changes to this policy",
    content: <p>This policy may be updated when the website, platform, providers or legal requirements change. Material changes should be identified by updating the effective date and, where appropriate, notifying affected customers through an agreed channel.</p>,
  },
  {
    id: "contact",
    title: "Contact information",
    content: <><p>General privacy enquiries can currently be sent to <a href="mailto:info@operionos.com">info@operionos.com</a>.</p><p><Placeholder>legal entity, postal address, dedicated data-protection contact and DPO status.</Placeholder></p></>,
  },
  {
    id: "effective-date",
    title: "Effective date",
    content: <p>This policy is effective from {EFFECTIVE_DATE}. It requires review by the company&apos;s legal or privacy adviser, including completion of every marked item.</p>,
  },
];

const legalSections = [
  {
    id: "introduction",
    title: "Introduction",
    content: <><p>These terms govern access to the public Operion website, prepared demonstrations and, where no separate written customer agreement applies, evaluation access to the Operion platform. A signed customer agreement takes priority if it conflicts with these website terms.</p><p>The Operion legal entity has not been identified in the current public configuration. <Placeholder>contracting legal entity, registration details and registered address.</Placeholder></p></>,
  },
  {
    id: "definitions",
    title: "Definitions",
    content: <ul><li><strong>Operion</strong> means the legal entity operating the website and service, once identified above.</li><li><strong>Service</strong> means the Operion website, demonstration and contract-intelligence platform made available to a user.</li><li><strong>Customer</strong> means an organisation authorised to evaluate or use the Service.</li><li><strong>Customer Content</strong> means documents, data and instructions supplied by or for a Customer.</li><li><strong>Output</strong> means information produced from use of the Service, including extracted or generated contract intelligence.</li></ul>,
  },
  {
    id: "website-use",
    title: "Use of the website",
    content: <><p>The public website provides product information and prepared demonstrations for general information and evaluation. Users must not misuse the website, interfere with its operation, attempt unauthorised access, or use its content unlawfully.</p><p>Illustrative scenarios, exposure figures and prepared demo data are not customer data and must not be treated as statements about actual organisations or events.</p></>,
  },
  {
    id: "platform",
    title: "Operion platform and service",
    content: <p>Operion structures contract documents into evidence-linked information such as clauses, obligations, deadlines, risks and summaries. Available capabilities depend on the applicable deployment, permissions and agreement. Product direction and roadmap material are not commitments to deliver a capability or delivery date.</p>,
  },
  {
    id: "accounts",
    title: "Customer accounts",
    content: <p>Private platform functions require an authenticated account and active organisation membership. Users are responsible for maintaining the confidentiality of their credentials and for promptly reporting suspected unauthorised access. Access rights may be limited by organisation role and permission.</p>,
  },
  {
    id: "responsibilities",
    title: "Customer responsibilities",
    content: <p>Customers are responsible for authorised use of their accounts, the legality and quality of Customer Content, reviewing Outputs before relying on them, and configuring their workflows to meet their own contractual, regulatory and professional obligations. Customers must ensure that their users have authority to upload and process documents.</p>,
  },
  {
    id: "content",
    title: "Customer Content",
    content: <><p>Customers retain their existing rights in Customer Content. They provide the permissions necessary for Operion and its configured providers to host, process and transmit that content solely to provide, secure and support the Service under the applicable agreement.</p><p>Detailed ownership, return, deletion and processing instructions must be established in the customer agreement. <Placeholder>final Customer Content licence and data-return terms.</Placeholder></p></>,
  },
  {
    id: "intellectual-property",
    title: "Intellectual property",
    content: <><p>Operion and its licensors retain their rights in the website, software, design, documentation, methods and other service materials, excluding Customer Content. No right is granted except the limited right to access the Service as authorised.</p><p><Placeholder>contracting entity ownership, trademark position, feedback licence and final Output ownership terms.</Placeholder></p></>,
  },
  {
    id: "confidentiality",
    title: "Confidentiality",
    content: <><p>Private customer documents may contain confidential information and are handled through protected application routes and private storage. Complete confidentiality obligations, permitted disclosures, exclusions and duration must be defined in the applicable customer agreement.</p><p><Placeholder>mutual confidentiality terms.</Placeholder></p></>,
  },
  {
    id: "ai-outputs",
    title: "AI-assisted and automated outputs",
    content: <><p>The Service combines deterministic processing with optional AI-assisted functions where configured. Outputs may be incomplete, inaccurate or unsuitable for a particular decision. Users must review relevant source evidence and apply qualified human judgement before acting on an Output.</p><p>Operion does not represent a confidence score, recommendation or generated explanation as a guarantee of accuracy, outcome or contractual compliance.</p></>,
  },
  {
    id: "no-legal-advice",
    title: "No legal advice",
    content: <p>Operion provides software and contract-intelligence tools. The website, Service and Outputs are not legal advice and do not create a lawyer-client relationship. Customers remain responsible for obtaining legal, financial, technical or other professional advice where appropriate.</p>,
  },
  {
    id: "availability",
    title: "Availability and service limitations",
    content: <p>The Service may be changed, interrupted or unavailable, and some functions depend on third-party infrastructure. Operion does not make a public guaranteed-uptime, disaster-recovery, support-response or service-level commitment. Any binding service level must be stated in a separate customer agreement.</p>,
  },
  {
    id: "acceptable-use",
    title: "Acceptable use",
    content: <p>Users must not use the Service to violate law or third-party rights; process content without authority; introduce malicious code; probe or bypass security; access another organisation&apos;s information; overload the Service; reverse engineer it except where law prevents restriction; or use Outputs to make unlawful decisions about individuals.</p>,
  },
  {
    id: "suspension",
    title: "Suspension and termination",
    content: <><p>Access may be restricted where reasonably necessary to address unauthorised use, security risk, legal requirements or material breach. Contractual notice, cure, termination, data export and deletion rights must be set out in the applicable customer agreement.</p><p><Placeholder>final suspension, termination and post-termination terms.</Placeholder></p></>,
  },
  {
    id: "data-protection",
    title: "Data protection",
    content: <p>Personal data is handled as described in the <Link to="/privacy">Privacy Policy</Link>. Customer deployments may require separate data-processing terms that identify the parties&apos; roles, processing instructions, security measures, subprocessors, transfer safeguards, assistance and deletion obligations.</p>,
  },
  {
    id: "third-parties",
    title: "Third-party services",
    content: <><p>The Service relies on configured third-party infrastructure and may link to external websites. Operion does not control external websites. Provider-specific terms may apply to customer-approved integrations or deployment choices.</p><p><Placeholder>contractual list of approved third-party services and responsibility allocation.</Placeholder></p></>,
  },
  {
    id: "liability",
    title: "Liability",
    content: <><p>No limitation or exclusion of liability is stated in these website terms because an appropriate position depends on the contracting entity, governing law, customer agreement and mandatory legal protections.</p><p><Placeholder>legally reviewed warranties, disclaimers, exclusions, liability cap and liabilities that cannot lawfully be limited.</Placeholder></p></>,
  },
  {
    id: "indemnification",
    title: "Indemnification",
    content: <><p>No indemnity obligation is created by this section. Any indemnification relating to Customer Content, infringement, misuse or third-party claims must be proportionate, legally reviewed and included in the applicable customer agreement.</p><p><Placeholder>indemnity scope, exclusions, procedure and control of claims, if appropriate.</Placeholder></p></>,
  },
  {
    id: "governing-law",
    title: "Governing law and jurisdiction",
    content: <><p>The governing law and courts have not been identified in the current public configuration.</p><p><Placeholder>governing law, exclusive or non-exclusive jurisdiction, and any mandatory consumer rights.</Placeholder></p></>,
  },
  {
    id: "changes",
    title: "Changes to these terms",
    content: <p>These terms may be updated as the website, Service or legal requirements change. The effective date will be updated when changes are published. Material changes affecting contracted customers should be handled through the notice and change process in their customer agreement.</p>,
  },
  {
    id: "contact",
    title: "Contact",
    content: <><p>General enquiries about these terms can be sent to <a href="mailto:info@operionos.com">info@operionos.com</a>.</p><p><Placeholder>legal entity, registered address and formal legal-notice details.</Placeholder></p></>,
  },
  {
    id: "effective-date",
    title: "Effective date",
    content: <p>These terms are effective from {EFFECTIVE_DATE}. They require review by the company&apos;s legal adviser, including completion of every marked item.</p>,
  },
];

export function PrivacyPage() {
  return <PolicyPage eyebrow="PRIVACY POLICY" title="Privacy at Operion" intro="How information is handled across the public website, customer accounts and contract-intelligence platform." counterpart={{ to: "/legal", label: "Read the Legal / Terms page" }} sections={privacySections} />;
}

export function LegalPage() {
  return <PolicyPage eyebrow="LEGAL / TERMS" title="Terms of use" intro="The terms for the Operion website, prepared demonstrations and platform evaluation." counterpart={{ to: "/privacy", label: "Read the Privacy Policy" }} sections={legalSections} />;
}