services:
  - type: web
    name: operionos-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
