import React, { useMemo, useState } from "react";
import { Background, Controls, Handle, MarkerType, MiniMap, Position, ReactFlow } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { DemoBadge } from "../../demo/DemoUI";

function NodeCard({ data }) {
  return <div className={`od-graph-node od-graph-node-${data.type}${data.isSelected ? " is-selected" : ""}`} role={data.contractId || data.aircraftId ? "button" : undefined} tabIndex={data.contractId || data.aircraftId ? 0 : undefined}><Handle type="target" position={Position.Left}/><span>{data.type === "linkedAircraft" ? "linked aircraft" : data.type}</span><strong>{data.label}</strong><small>{data.subtitle}</small><DemoBadge tone="success">{data.status}</DemoBadge>{data.linkedAircraftCount > 1 && <em>✈ {data.linkedAircraftCount} aircraft</em>}<Handle type="source" position={Position.Right}/></div>;
}

const nodeTypes = { operion: NodeCard };

export default function ContractDependencyGraph({ graph, selectedContractId, onSelectContract, onSelectAircraft }) {
  const [selected,setSelected] = useState(null);
  const nodes = useMemo(()=>{const indexes={aircraft:0,contract:0,supplier:0,linkedAircraft:0,obligation:0,dependency:0};const columns={aircraft:20,contract:270,supplier:540,linkedAircraft:540,obligation:810,dependency:1080};return graph.nodes.map(item=>{const index=indexes[item.type]++;const count=graph.nodes.filter(node=>node.type===item.type).length;return {id:item.id,type:"operion",position:{x:columns[item.type],y:165+index*118-(count-1)*59},data:{...item,isSelected:item.contractId===selectedContractId}};});},[graph,selectedContractId]);
  const edges = useMemo(()=>graph.edges.map(item=>({ ...item, label:item.relationship, markerEnd:{type:MarkerType.ArrowClosed}, style:{stroke:item.relationship==="insures"?"#5678dd":"#7657ec",strokeWidth:1.5}, labelStyle:{fill:"#59637b",fontSize:10,fontWeight:700}, animated:item.relationship==="depends on" })),[graph]);
  const selectNode = (node) => { setSelected({kind:"node",...node.data}); if (node.data.contractId) onSelectContract?.(node.data.contractId); if (node.data.aircraftId) onSelectAircraft?.(node.data.aircraftId); };
  return <div className="od-graph-wrap"><div className="od-graph-canvas"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView minZoom={0.3} maxZoom={1.8} onNodeClick={(_,node)=>selectNode(node)} onNodeKeyDown={(event,node)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();selectNode(node);}}} onEdgeClick={(_,edge)=>setSelected({kind:"edge",...graph.edges.find(item=>item.id===edge.id)})} nodesDraggable={false} proOptions={{hideAttribution:true}}><Background color="#dfe4f2" gap={22}/><Controls showInteractive={false}/><MiniMap pannable zoomable nodeColor="#7657ec"/></ReactFlow></div><aside className="od-graph-inspector"><DemoBadge>DEMO RELATIONSHIP</DemoBadge>{selected?.kind==="node"?<><span>{selected.type === "linkedAircraft" ? "Linked aircraft" : selected.type}</span><h3>{selected.label}</h3><p>{selected.subtitle}</p>{selected.contractId&&<button className="od-button od-button-primary" type="button" onClick={()=>onSelectContract?.(selected.contractId)}>Preview contract</button>}{selected.aircraftId&&<button className="od-button od-button-primary" type="button" onClick={()=>onSelectAircraft?.(selected.aircraftId)}>Select aircraft</button>}</>:selected?.kind==="edge"?<><span>Relationship</span><h3>{selected.relationship}</h3><p>{graph.nodes.find(item=>item.id===selected.source)?.label} → {graph.nodes.find(item=>item.id===selected.target)?.label}</p><p>Prepared relationship fixture. No production evidence is claimed.</p></>:<><span>Dependency inspector</span><h3>Select a contract or aircraft</h3><p>Open a concise contract preview or move directly to another affected aircraft.</p></>}</aside></div>;
}
