import React, { useState } from "react";
import { Link } from "react-router-dom";
import { DEMO_CONTRACT_INTELLIGENCE } from "../../lib/demoContractIntelligence";

function TermDrawer({ term, contract, onClose }) {
  if (!term) return null;
  const clause = contract.clauses.find((item) => item.id === term.clauseId);
  const risk = contract.riskRecords.find((item) => item.id === term.riskId);
  return <div className="op-econ-drawer-backdrop" role="presentation" onClick={onClose}><aside className="op-econ-drawer" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><button type="button" aria-label="Close commercial term" onClick={onClose}>×</button><span>CONTRACT ECONOMICS · COMMERCIAL TERM</span><h2>{term.type}</h2><dl>{[["Contract", contract.title], ["Counterparty", contract.counterparty], ["Contractual value", contract.value], ["Modeled exposure", risk.exposure], ["Term", term.description], ["Trigger", term.effectiveDate], ["Owner", term.owner], ["Opportunity", term.opportunity], ["Confidence", risk.confidence]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>Potential commercial opportunity only. Savings, spend, payment, invoice, and external benchmark data are not available in the current demo.</p><Link to="/demo/contracts/demo-aircraft-lease">View source clause {clause.number} ↗</Link></aside></div>;
}

export default function ContractEconomicsWorkspace() {
  const contract = DEMO_CONTRACT_INTELLIGENCE["demo-aircraft-lease"];
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState(null);
  const [answer, setAnswer] = useState("");
  const exposure = contract.riskRecords.reduce((total, item) => total + item.exposureValue, 0);
  const terms = contract.commercialTerms.filter((item) => !query || `${item.type} ${item.description} ${item.owner} ${item.opportunity}`.toLowerCase().includes(query.toLowerCase()));
  const responses = {
    "Where are the biggest commercial opportunities?": "Renewal pricing review, delivery-damages review, and service-credit review are evidence-backed potential opportunities.",
    "Which contracts have the highest contractual value?": `${contract.title} represents ${contract.value} contractual value. This is not actual spend.`,
    "Which renewals need pricing review?": "The auto-renewal notice window supports a high-priority commercial and legal review.",
    "Which contracts contain liquidated damages?": "Clause 7.3 contains the delivery-delay liquidated damages mechanism.",
    "Is this a confirmed saving or only a potential opportunity?": "All opportunities shown are potential contract-derived opportunities; realized savings are not available in this demo.",
  };
  return <section className="op-econ-workspace"><div className="op-econ-heading"><div><span>CONTRACT ECONOMICS & SAVINGS INTELLIGENCE</span><h1>Commercial value hidden inside the contract.</h1><p>Contractual value, modeled exposure, evidence-backed terms, and potential opportunities. This is not spend, invoices, or realized savings data.</p></div><div><span>CONTRACT PORTFOLIO COMMERCIAL HEALTH</span><strong>Watch</strong><small>Material modeled exposure and renewal terms require commercial review.</small></div></div><div className="op-econ-metrics">{[["Contractual value", contract.value], ["Modeled exposure", `€${(exposure / 1000000).toFixed(2)}M`], ["Commercial opportunities", contract.commercialTerms.length], ["Renewal reviews", contract.lifecycle.length], ["Financial actions", contract.recommendations.filter((item) => item.status !== "Completed").length], ["Financial terms", terms.length]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="op-econ-note">Savings are not calculated from actual spend in this demo. Commercial opportunities are derived from contractual terms and modeled data only.</p><input className="op-econ-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search contracts, counterparties, terms..." aria-label="Search contract economics"/><section className="op-econ-terms"><h2>Commercial Terms Watch</h2>{terms.map((term) => <button type="button" key={term.id} onClick={() => setSelected(term)}><span>{term.opportunity} · {term.effectiveDate}</span><strong>{term.type}</strong><p>{term.description}</p><em>{term.recommendation}</em></button>)}</section><div className="op-econ-grid"><div><h3>Renewal Economics</h3><p>Auto-renewal notice window: {contract.lifecycle[0].renewalDate}. Review pricing and commercial terms before the notice deadline.</p><Link to="/demo?view=lifecycle">Open lifecycle intelligence ↗</Link></div><div><h3>Commercial Risk</h3>{contract.riskRecords.filter((risk) => risk.exposureValue >= 180000).map((risk) => <Link key={risk.id} to="/demo?view=exposure"><strong>{risk.title}</strong><span>{risk.exposure} · {risk.consequence}</span></Link>)}</div><div><h3>Commercial Actions</h3><Link to="/demo?view=actions">Review evidence-linked commercial actions ↗</Link><Link to="/demo?view=negotiation">Open negotiation preparation ↗</Link><Link to="/demo?view=vendors">View vendor commercial position ↗</Link></div></div><section className="op-econ-ask"><h2>Ask Operion</h2>{Object.keys(responses).map((prompt) => <button type="button" key={prompt} onClick={() => setAnswer(responses[prompt])}>{prompt}</button>)}{answer && <div><span>AI ANALYSIS · CONTRACT-GROUNDED ECONOMICS</span><p>{answer}</p></div>}</section><TermDrawer term={selected} contract={contract} onClose={() => setSelected(null)} /></section>;
}
